<a href="https://colab.research.google.com/github/BrendoEnomoto/Machine-Learning-Projects/blob/main/Classifica%C3%A7%C3%A3o/liver_patient.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## liver_patient

**Sobre o Dataset**
* O dataset utilizado se chama liverpatient-2.csv e, como o nome sugere, contém dados de pacientes com doença hepática. O objetivo é usar esses dados para construir modelos de aprendizado de máquina que possam prever a classe da doença.[Disponivel no Kaggle](https://www.kaggle.com/datasets/anurag98k/liver-patient)



O código em seu notebook realiza a análise de dados de pacientes com doença hepática usando aprendizado de máquina para prever a classe da doença.
**1. Importação e Preparação dos Dados:**

* Importa a biblioteca `pandas` para manipulação de dados.
* Lê os dados do arquivo `liverpatient-2.csv` em um DataFrame `df`.
* Exibe as primeiras linhas, dimensões, informações sobre as colunas e estatísticas descritivas do DataFrame para entender melhor os dados.
* Converte a coluna `V2` (provavelmente representando o gênero) de valores categóricos ('Female', 'Male') para numéricos (0, 1) usando um dicionário para mapeamento.

**2. Modelagem e Avaliação:**

* Importa as bibliotecas necessárias para construir e avaliar modelos de aprendizado de máquina:
    * `RandomForestClassifier` e `SVC` para os modelos.
    * `StratifiedKFold` para validação cruzada estratificada, garantindo a distribuição equilibrada das classes nas dobras.
    * `RandomizedSearchCV` para encontrar os melhores hiperparâmetros dos modelos de forma eficiente.
    * `f1_score` como métrica de avaliação.
* Cria e treina um modelo **SVC (Support Vector Classifier)**:
    * Define o modelo `svc_classifier`.
    * Define a estratégia de validação cruzada com 10 dobras.
    * Define o espaço de busca de hiperparâmetros.
    * Usa `RandomizedSearchCV` para encontrar os melhores hiperparâmetros com base na métrica F1.
    * Treina o modelo com os melhores hiperparâmetros encontrados.
    * Exibe o melhor F1 score, os melhores hiperparâmetros e o melhor estimador.
* Cria e treina um modelo **Random Forest Classifier**:
    * Segue o mesmo processo do SVC, com a diferença de usar o `RandomForestClassifier` e definir um espaço de busca de hiperparâmetros diferente.
    * Treina o modelo com os melhores hiperparâmetros encontrados.
    * Exibe o melhor F1 score, os melhores hiperparâmetros e o melhor estimador.

**Em resumo:**

O código realiza um processo de classificação para prever a classe da doença hepática em pacientes. Utiliza dois modelos de aprendizado de máquina (SVC e Random Forest) com técnicas de otimização de hiperparâmetros e validação cruzada para encontrar o modelo com o melhor desempenho. A métrica F1 é usada para avaliar o desempenho dos modelos.

In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/XP/bootcamp_eng_ML/liverpatient-2.csv')
df.head()

   V1      V2    V3   V4   V5  V6   V7   V8   V9   V10  Class
0  65  Female   0.7  0.1  187  16   18  6.8  3.3  0.90      1
1  62    Male  10.9  5.5  699  64  100  7.5  3.2  0.74      1
2  62    Male   7.3  4.1  490  60   68  7.0  3.3  0.89      1
3  58    Male   1.0  0.4  182  14   20  6.8  3.4  1.00      1
4  72    Male   3.9  2.0  195  27   59  7.3  2.4  0.40      1

In [ ]:
df.shape

(583, 11)

In [ ]:
df.isna().sum()

V1       0
V2       0
V3       0
V4       0
V5       0
V6       0
V7       0
V8       0
V9       0
V10      0
Class    0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 583 entries, 0 to 582
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   V1      583 non-null    int64
 1   V2      583 non-null    int64
 2   V3      583 non-null    float64
 3   V4      583 non-null    float64
 4   V5      583 non-null    int64
 5   V6      583 non-null    int64
 6   V7      583 non-null    int64
 7   V8      583 non-null    float64
 8   V9      583 non-null    float64
 9   V10     583 non-null    float64
 10  Class   583 non-null    int64
dtypes: float64(5), int64(6)
memory usage: 50.2 KB

In [ ]:
df.describe()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,Class
count,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000
mean,44.746141,0.756432,3.298799,1.486106,290.576329,80.713551,109.910806,6.483190,3.141852,0.947064,1.286449
std,16.189833,0.429603,6.209522,2.808498,242.937989,182.620356,288.918529,1.085451,0.795519,0.318492,0.452490
min,4.000000,0.000000,0.400000,0.100000,63.000000,10.000000,10.000000,2.700000,0.900000,0.300000,1.000000
25%,33.000000,1.000000,0.800000,0.200000,175.500000,23.000000,25.000000,5.800000,2.600000,0.700000,1.000000
50%,45.000000,1.000000,1.000000,0.300000,208.000000,35.000000,42.000000,6.600000,3.100000,0.947064,1.000000
75%,58.000000,1.000000,2.600000,1.300000,298.000000,60.500000,87.000000,7.200000,3.800000,1.100000,2.000000
max,90.000000,1.000000,75.000000,19.700000,2110.000000,2000.000000,4929.000000,9.600000,5.500000,2.800000,2.000000

In [ ]:
map_v2 = {
    'Female': 0,
    'Male': 1
}
df['V2'] = df['V2'].map(map_v2)

0      0
1      1
2      1
3      1
4      1
      ..
578    1
579    1
580    1
581    1
582    1
Name: V2, Length: 583, dtype: int64

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform
from scipy.stats import randint
from sklearn.metrics import f1_score, make_scorer

SVC e o Random Forest Classifier, com Random Search para
sintonia de hiperparâmetros e validação cruzada estratificada.

# Implementação SVC

In [ ]:
svc_classifier = SVC()

cv_strategy = StratifiedKFold(n_splits=10)

f1 = make_scorer(f1_score)

svc_parameters = {
    'kernel': ['sigmoid', 'poly', 'rbf', ],
    'C': uniform(1, 10)
}

svc_random_search = RandomizedSearchCV(
    estimator=svc_classifier,
    param_distributions=svc_parameters,
    n_iter=5,
    cv=cv_strategy,
    scoring=f1,
    random_state=5762
)
svc_random_search.fit(df.drop('Class', axis=1), df['Class'])

RandomizedSearchCV(cv=StratifiedKFold(n_splits=10, random_state=None, shuffle=False),
                   estimator=SVC(), n_iter=5,
                   param_distributions={'C': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x7bbffd185f10>,
                                        'kernel': ['sigmoid', 'poly', 'rbf']},
                   random_state=5762,
                   scoring=make_scorer(f1_score, response_method='predict'))

In [ ]:
svc_random_search.best_score_

0.8328180818081808

In [ ]:
svc_random_search.best_params_

{'C': 3.996689355015553, 'kernel': 'poly'}

In [ ]:
svc_random_search.best_estimator_

SVC(C=3.996689355015553, kernel='poly')

##Implementação Random Forest Classifier

In [ ]:
rf_classifier = RandomForestClassifier(random_state = 5762)

cv_strategy = StratifiedKFold(n_splits=10)

f1 = make_scorer(f1_score)

rf_parameters = {
    'n_estimators': randint(10, 1000),
    'bootstrap' : [True, False],
    'criterion': ['gini', 'entropy']
}

rf_random_search = RandomizedSearchCV(
    estimator=rf_classifier,
    param_distributions=rf_parameters,
    n_iter=5,
    cv=cv_strategy,
    scoring=f1,
    random_state=5762
)
rf_random_search.fit(df.drop('Class', axis=1), df['Class'])

RandomizedSearchCV(cv=StratifiedKFold(n_splits=10, random_state=None, shuffle=False),
                   estimator=RandomForestClassifier(random_state=5762),
                   n_iter=5,
                   param_distributions={'bootstrap': [True, False],
                                        'criterion': ['gini', 'entropy'],
                                        'n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7bbffcc13010>},
                   random_state=5762,
                   scoring=make_scorer(f1_score, response_method='predict'))

In [ ]:
rf_random_search.best_score_

0.7984322518413547

In [ ]:
rf_random_search.best_params_

{'bootstrap': True, 'criterion': 'gini', 'n_estimators': 488}

In [ ]:
rf_random_search.best_estimator_

RandomForestClassifier(n_estimators=488, random_state=5762)