<a href="https://colab.research.google.com/github/BrendoEnomoto/Machine-Learning-Projects/blob/main/Classifica%C3%A7%C3%A3o/Qualidade_dos_Vinhos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Qualidade dos Vinhos
Red Wine Quality Dataset: dinsponivelno kaggle pelo link:[Red Wine Quality](https://www.kaggle.com/datasets/lovishbansal123/red-wine-quality)

Objetivo: O conjunto de dados contém informações sobre as propriedades físico-químicas de vinhos tintos, com o objetivo de prever a qualidade do vinho.
Estrutura:
Cada linha representa uma amostra única de vinho.
Cada coluna representa um atributo específico do vinho, como acidez, teor de açúcar, pH, teor alcoólico, etc.
A coluna 'quality' contém a avaliação da qualidade do vinho por especialistas e é a variável alvo para tarefas de modelagem preditiva.
Utilização: É amplamente utilizado para:
Análise exploratória de dados
Tarefas de classificação (prever a qualidade do vinho em categorias)
Tarefas de regressão (prever a qualidade do vinho em uma escala numérica)
## Parte 1: Carregamento e Análise Exploratória dos Dados

**Importando bibliotecas:**

- `pandas` para manipulação de dados.
- `MinMaxScaler` do `sklearn.preprocessing` para normalização dos dados.

**Carregando o dataset:**

- O dataset `winequality-red.csv` é carregado usando `pd.read_csv()`.

**Análise exploratória:**

- `red_wine_df.head()` exibe as primeiras linhas do dataset.
- `red_wine_df.shape` mostra o número de instâncias e atributos.
- `red_wine_df.info()` fornece informações sobre os tipos de dados das colunas.
- `red_wine_df.describe()` calcula estatísticas descritivas.
- `red_wine_df.corr(method='pearson')` calcula a correlação entre as variáveis.
- É feita uma contagem de instâncias com qualidade do vinho igual a 5.


## Parte 2: Pré-processamento dos Dados

**Normalização:**

- `MinMaxScaler` é aplicado para normalizar os dados numéricos, ajustando os valores entre 0 e 1.
- O menor valor para a variável "fixed acidity" após a normalização é obtido.


## Parte 3: Modelagem e Avaliação

**Divisão dos dados:**

- `train_test_split` é usado para dividir o dataset em conjuntos de treino e teste.

**Modelos:**

- **KNN:** Um modelo KNN é treinado e avaliado usando `accuracy_score`.
- **Árvore de Decisão:** Uma árvore de decisão é treinada e avaliada.
- **Floresta Randômica:** Uma floresta randômica é treinada e avaliada.
- **SVM:** Um modelo SVM é treinado e avaliado.
- **Rede Neural:** Uma rede neural MLP é treinada e avaliada.


## Parte 4: Modificação do Dataset e Nova Avaliação

**Transformação em sistema binário:**

- A coluna "quality" é modificada para representar um sistema binário: vinhos com nota maior que 5 são considerados "bons" (1) e os demais "ruins" (0).

**Normalização:**

- O dataset modificado é normalizado usando `MinMaxScaler`.

**Divisão dos dados:**

- O dataset é dividido em conjuntos de treino e teste.

**Floresta Randômica:**

- Uma floresta randômica é treinada com o dataset modificado e avaliada usando `accuracy_score`.


**Resumo:**

O código realiza uma análise exploratória de um dataset de vinhos, aplica técnicas de pré-processamento, treina e avalia diferentes modelos de classificação para prever a qualidade do vinho. Finalmente, o dataset é modificado para um problema de classificação binária e um modelo de floresta randômica é treinado e avaliado com essa nova configuração.

In [ ]:
import pandas as pd

red_wine_df = pd.read_csv('winequality-red.csv', sep=';')

red_wine_df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

**No dataset utilizado para o desafio, quantas instâncias e atributos existem, respectivamente?**

In [ ]:
red_wine_df.shape

(1599, 12)

**Quantos tipos diferentes de dados existem no dataset do desafio?**

In [ ]:
red_wine_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [ ]:
red_wine_df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000


**Sobre o coeficiente de correlação de Pearson entre as variáveis "fixed acidity" e "pH", é CORRETO afirmar:**

**Sobre o coeficiente de correlação de Pearson entre as variáveis "quality" e "alcohol", mesmo sendo reduzido, é CORRETO dizer:**

In [ ]:
red_wine_df.corr(method='pearson')

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
fixed acidity,1.000000,-0.256131,0.671703,0.114777,0.093705,-0.153794,-0.113181,0.668047,-0.682978,0.183006,-0.061668,0.124052
volatile acidity,-0.256131,1.000000,-0.552496,0.001918,0.061298,-0.010504,0.076470,0.022026,0.234937,-0.260987,-0.202288,-0.390558
citric acid,0.671703,-0.552496,1.000000,0.143577,0.203823,-0.060978,0.035533,0.364947,-0.541904,0.312770,0.109903,0.226373
residual sugar,0.114777,0.001918,0.143577,1.000000,0.055610,0.187049,0.203028,0.355283,-0.085652,0.005527,0.042075,0.013732
chlorides,0.093705,0.061298,0.203823,0.055610,1.000000,0.005562,0.047400,0.200632,-0.265026,0.371260,-0.221141,-0.128907
free sulfur dioxide,-0.153794,-0.010504,-0.060978,0.187049,0.005562,1.000000,0.667666,-0.021946,0.070377,0.051658,-0.069408,-0.050656
total sulfur dioxide,-0.113181,0.076470,0.035533,0.203028,0.047400,0.667666,1.000000,0.071269,-0.066495,0.042947,-0.205654,-0.185100
density,0.668047,0.022026,0.364947,0.355283,0.200632,-0.021946,0.071269,1.000000,-0.341699,0.148506,-0.496180,-0.174919
pH,-0.682978,0.234937,-0.541904,-0.085652,-0.265026,0.070377,-0.066495,-0.341699,1.000000,-0.196648,0.205633,-0.057731
sulphates,0.183006,-0.260987,0.312770,0.005527,0.371260,0.051658,0.042947,0.148506,-0.196648,1.000000,0.093595,0.251397
alcohol,-0.061668,-0.202288,0.109903,0.042075,-0.221141,-0.069408,-0.205654,-0.496180,0.205633,0.093595,1.000000,0.476166
quality,0.124052,-0.390558,0.226373,0.013732,-0.128907,-0.050656,-0.185100,-0.174919,-0.057731,0.251397,0.476166,1.000000

**Quantas instâncias existem para a qualidade do vinho igual a 5?**

In [ ]:
red_wine_df[red_wine_df['quality'] == 5]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
5,7.4,0.660,0.00,1.8,0.075,13.0,40.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1582,6.1,0.715,0.10,2.6,0.053,13.0,27.0,0.99362,3.57,0.50,11.9,5
1583,6.2,0.460,0.29,2.1,0.074,32.0,98.0,0.99578,3.33,0.62,9.8,5
1589,6.6,0.725,0.20,7.8,0.073,29.0,79.0,0.99770,3.29,0.54,9.2,5
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5

**Aplique o modelo de normalização MinMaxScaler com os valores "default" para os dados de entrada. Qual é o menor valor para a variável "fixed acidity"?**

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler( )

red_wine_df_scaled = scaler.fit_transform(red_wine_df)

red_wine_df_scaled = pd.DataFrame(red_wine_df_scaled, columns=red_wine_df.columns)

red_wine_df_scaled['fixed acidity'].max()

1.0

In [ ]:
from sklearn.model_selection import train_test_split

X = red_wine_df.drop('quality', axis=1)
y = red_wine_df['quality']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1)

**Implementação do KNN**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

clf_KNN = KNeighborsClassifier(n_neighbors=5)

clf_KNN.fit(X_train, y_train)

y_pred = clf_KNN.predict(X_test)

accuracy_score(y_test, y_pred)

0.5041666666666667

**Implementação Algoritmo Árvore de Decisão**

In [ ]:
from sklearn.tree import DecisionTreeClassifier

clf_arvore = DecisionTreeClassifier()

clf_arvore.fit(X_train, y_train)

y_pred = clf_arvore.predict(X_test)

accuracy_score(y_test, y_pred)

0.6020833333333333

**Implementação Algoritmo Floresta Randônica**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

clf_floresta = RandomForestClassifier(max_depth=10, random_state=1)

clf_floresta.fit(X_train, y_train)

y_pred = clf_floresta.predict(X_test)

accuracy_score(y_test, y_pred)

0.68125

**Implementação Algoritmo SVM**

In [ ]:
from sklearn.svm import SVC

clf_svm=SVC(gamma='auto',kernel='rbf')

clf_svm.fit(X_train, y_train)

y_pred = clf_svm.predict(X_test)

accuracy_score(y_test, y_pred)

0.5645833333333333

In [ ]:
from sklearn.neural_network import MLPClassifier

clf_mlp = MLPClassifier(alpha=1e-5, hidden_layer_sizes=(5,5), random_state=1)

clf_mlp.fit(X_train, y_train)

y_pred = clf_mlp.predict(X_test)

accuracy_score(y_test, y_pred)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

0.4875

**Modifique o dataset para um sistema binário que considere vinhos com nota maior do que 5 (6, 7, 8) sejam bons e menores ou igual a 5 ruins (5, 4, 3). Aplique o modelo da floresta randômica. Qual é o valor mais próximo da acurácia do modelo para esse novo dataset?**

In [ ]:
red_wine_df = pd.read_csv('winequality-red.csv', sep=';')
red_wine_df['quality'] = red_wine_df['quality'].apply(lambda x: 1 if x > 5 else 0)
red_wine_df['quality'].value_counts()

quality
1    855
0    744
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler( )

red_wine_df_scaled = scaler.fit_transform(red_wine_df)

red_wine_df_scaled = pd.DataFrame(red_wine_df_scaled, columns=red_wine_df.columns)

In [ ]:
from sklearn.model_selection import train_test_split

X = red_wine_df.drop('quality', axis=1)
y = red_wine_df['quality']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

clf_floresta = RandomForestClassifier(max_depth=10, random_state=1)

clf_floresta.fit(X_train, y_train)

y_pred = clf_floresta.predict(X_test)

accuracy_score(y_test, y_pred)

0.8041666666666667